### ISSUE TITLE
getfrom

### ISSUE THREAD

**Issue by alancrawford** [ChrisRackauckas/ParallelDataTransfer.jl#1]
Hi,

I was wondering if you could help me understand some unexpected behaviour i am seeing from `getfrom()`.

The issue is that when i update a field remotely and then use `getfrom()`, it doesn't give me the correct object. However, when i use the commands that define `getfrom()` directly, I get the expected result.

Here is a toy example to illustrate. I open julia -p 3, then type:

``` julia
@everywhere using ParallelDataTransfer
@everywhere type foo
    a
    b
    c
end
```

Then I define a vector of foo's and send it too all workers:

``` julia
srand(3)
foo_vec = [foo(rand(3),rand(3),rand(3)) for n in 1:3]
sendto(workers(),foo_vec=foo_vec)
```

To check it worked:

``` julia
julia> foo_vec[3].c
3-element Array{Float64,1}:
 0.999508
 0.634155
 0.704937

julia> getfrom(2, :c, mod=Main.foo_vec[3])
3-element Array{Float64,1}:
 0.999508
 0.634155
 0.704937
```

Now I mutate field `c` in `foo_vec[3]` on worker 2 and assign it `myfoo_3c` on master processor

``` julia
julia> remotecall(2, ()->Main.foo_vec[3].c=ones(3))
RemoteRef{Channel{Any}}(2,1,55)

julia> myfoo_3c = remotecall_fetch(2, ()->Main.foo_vec[3].c) 
3-element Array{Float64,1}:
 1.0
 1.0
 1.0
```

Now suppose i try to use `getfrom()`:

``` julia
julia> myfoo_3c = getfrom(2,:c,  mod=Main.foo_vec[3])
3-element Array{Float64,1}:
 0.999508
 0.634155
 0.704937
```

As you can see it gives me the unadjusted field. Which seems a bit puzzling. I wondered if differences due to using `@spawnat` in `getfrom()` were driving this. So I defined a new function:

``` julia
julia> @everywhere getfrom_rcf(p::Int, nm::Symbol; mod=Main) = remotecall_fetch(p,()->getfield(mod,nm))

julia> myfoo_3c = getfrom_rcf(2,:c,  mod=Main.foo_vec[3])
3-element Array{Float64,1}:
 0.999508
 0.634155
 0.704937

julia> test_rcf = remotecall_fetch(2, ()->getfield(Main.foo_vec[3],:c))
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> test_spawnat = fetch(@spawnat(2, getfield(Main.foo_vec[3], :c)))
3-element Array{Float64,1}:
 1.0
 1.0
 1.0
```

So, naively, it looks as though something changes to the command when called through a function. Any idea why this is happening/how to get a version of `getfrom()` to pass the field? 

Thanks 
Alan

PS. I should say i am using latest stable Julia:  v0.4.6 on a macbook air in case you don't get same behaviour running these commands.

**Comment by ChrisRackauckas** [comment]
The package is setup for v0.5-RC right now. If you check the tests, you'll see they fail on v0.4.6 but pass on v0.5. It's because of the RemoteRef/Future changes, so they can't easily be simultaneously supported. But v0.5 will be out pretty soon!

**Comment by alancrawford** [comment]
Thanks Chris.

I just downloaded v0.5-rc2 and the ParallelDataTransfer repository.

I ran the specific code that demonstrates the behaviour and - at least in my case - the issue arises on v0.5 too. Here is the output:

``` julia
Last login: Fri Aug 19 16:08:50 on ttys001
exec '/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia'
➜  ~ exec '/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc2+0 (2016-08-12 11:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> 

julia> @everywhere using ParallelDataTransfer
WARNING: replacing module ParallelDataTransfer
WARNING: replacing module ParallelDataTransfer

julia> @everywhere type foo
           a
           b
           c
       end

julia> 

julia> foo_vec = [foo(rand(3),rand(3),rand(3)) for n in 1:3];

julia> sendto(workers(),foo_vec=foo_vec);

julia> 

julia> foo_vec[3].c
3-element Array{Float64,1}:
 0.539566 
 0.309477 
 0.0225731

julia> getfrom(2, :c, mod=Main.foo_vec[3])
3-element Array{Float64,1}:
 0.539566 
 0.309477 
 0.0225731

julia> 

julia> # This is fine. Now redefine Main.foo_vec[3].c on worker 2.

julia> 

julia> remotecall(()->Main.foo_vec[3].c=ones(3),2)
Future(2,1,16,Nullable{Any}())

julia> remotecall_fetch(()->Main.foo_vec[3].c,2) # Confirms the change
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> getfrom(2, :c, mod=Main.foo_vec[3]) # Expected vector of ones!
3-element Array{Float64,1}:
 0.539566 
 0.309477 
 0.0225731
```

**Comment by ChrisRackauckas** [comment]
I see. It looks like the tests miss this case. I'll look into it. Submit a PR if you find out what's going on before me (or at least notify me of the right direction). Thanks for pointing this out!

**Comment by alancrawford** [comment]
I will keep on poking around - they only real difference as far as i can tell so far is that the behaviour of remotefetch_call() behaviour is changed when wrapped in a function... 

On 19 Aug 2016, at 16:15, Christopher Rackauckas notifications@github.com wrote:

I see. It looks like the tests miss this case. I'll look into it. Submit a PR if you find out what's going on before me (or at least notify me of the right direction). Thanks for pointing this out!

**Comment by alancrawford** [comment]
More precisely, the issue seems to be from using `getfield(mod,nm)` inside `remotecall_fetch()` when wrapped in a function. If i hardcode the field and wrap `remotecall_fetch()` in a function, as i have in the function `getme(p)` below then I also get the expected results. Here is some output from the (bit more simplified) example

``` julia
Last login: Fri Aug 19 17:58:40 on ttys001
exec '/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia'
➜  ~ exec '/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc2+0 (2016-08-12 11:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> import ParallelDataTransfer

julia> @everywhere using ParallelDataTransfer

julia> @everywhere type foo
           a
           b
           c
       end

julia> foo1 = foo(rand(3),rand(3),rand(3));  # Define foo1

julia> ParallelDataTransfer.sendto(workers(),foo1=foo1);  # Put foo_vec on all workers

julia> foo1.c                                # For later reference
3-element Array{Float64,1}:
 0.569908
 0.4924  
 0.9001  

julia> remotecall(()->Main.foo1.c=ones(3),2)  # Mutate Main.foo1.c on worker 2.  
Future(2,1,8,Nullable{Any}())

julia> remotecall_fetch(()->Main.foo1.c,2)   # Confirms the change and works as expected
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> # Define new function that only take worker number as an argument - the rest hardcoded

julia> getme(p::Int64) = remotecall_fetch(()->Main.foo1.c,p)
getme (generic function with 1 method)

julia> getme(2) 
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> # Or - using function that defines getfrom() in ParallelDataTransfer

julia>  fetch(@spawnat(2, getfield(Main.foo1, :c))) # Also gives the mutated vector
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> # However, this doesn't give ones(3) 

julia> ParallelDataTransfer.getfrom(2, :c, mod=Main.foo1) 
3-element Array{Float64,1}:
 0.569908
 0.4924  
 0.9001  
```

I must say that I am not sure what the issue is - is it worth asking julia users on google groups as the issue doesn't seem to be with your package but perhaps with julia internals?

Thanks
alan

**Comment by ChrisRackauckas** [comment]
It may be worth pointing this out there. Though this may be a scoping issue.

**Comment by ChrisRackauckas** [comment]
I took a look at it and couldn't quite find out what it is. @spencerlyon2, you authored some of these originally, do you have any idea what might be going on here?

**Comment by ChrisRackauckas** [comment]
I've identified what the bug is, but I need to think of a good API idea to prevent it. What tipped me off is this:

``` julia
julia> myfoo = getfrom(2,:foo_vec,  mod=Main)
3-element Array{foo,1}:
 foo([0.811698,0.988432,0.807622],[0.970091,0.140061,0.509444],[0.0586974,0.00425796,0.974638])
 foo([0.557225,0.464422,0.287509],[0.296674,0.0740614,0.933823],[0.908625,0.487018,0.998337])
 foo([0.778678,0.413636,0.453905],[0.352955,0.390674,0.555613],[1.0,1.0,1.0])
```

So it actually works (you can see that `myfoo[3].c` is `[1.0,1.0,1.0]`). What isn't working is when you append extra field information into the `mod` argument. I.e. if it's just a module, then it works. If it's more than a module, then it won't.

But that makes it clear why it doesn't work. `fetch(@spawnat(2, getfield(Main.foo1, :c)))` is not the same as `ParallelDataTransfer.getfrom(2, :c, mod=Main.foo1)`, even though the latter calls the former. This is because, for a function call, Julia will actually evaluate expressions within a function call before performing the function. Therefore `ParallelDataTransfer.getfrom(2, :c, mod=Main.foo1)` will evaluate the `Main.foo1` and put in the ans, and instead will call `fetch(@spawnat(2, getfield(ans, :c)))`, which is different than what we want since `ans`  is `Main.foo1` on process 1, leading to the error.

To avoid the problem of Julia inlining the value, since we would clearly only want the semantic `Main.foo1` instead of the value, this call should be written as a macro instead of a function. Note that this problem likely only arises in `getfrom`. The other functions are okay since you really want to be sending and passing objects only to modules (otherwise name space issues would get tricky...). So the other functions can be kept the same using `mod=...` since it's unlikely any user would run into this issue, while there is a clear use case here (send only part of a type, instead of the whole thing).

**Comment by ChrisRackauckas** [comment]
Due to the issues of the previous comment, `getfrom` is deprecated in favor of the new `@getfrom` in cbf94b9167339c906d8274edf1c476d9ef81d3d7. The README was changed to reflect this. The example from this thread was added as a test. It computes correctly as follows:

``` julia
julia> @everywhere using ParallelDataTransfer

julia> @everywhere type foo
           a
           b
           c
       end

julia> srand(3);

julia> foo_vec = [foo(rand(3),rand(3),rand(3)) for n in 1:3]
3-element Array{foo,1}:
 foo([0.811698,0.988432,0.807622],[0.970091,0.140061,0.509444],[0.0586974,0.00425796,0.974638])
 foo([0.557225,0.464422,0.287509],[0.296674,0.0740614,0.933823],[0.908625,0.487018,0.998337])
 foo([0.778678,0.413636,0.453905],[0.352955,0.390674,0.555613],[0.999508,0.634155,0.704937])

julia> sendto(workers(),foo_vec=foo_vec)

julia> foo_vec[3].c
3-element Array{Float64,1}:
 0.999508
 0.634155
 0.704937

julia> @getfrom(2,foo_vec[3].c)
3-element Array{Float64,1}:
 0.999508
 0.634155
 0.704937

julia> remotecall(2, ()->Main.foo_vec[3].c=ones(3))
Future(2,1,385,Nullable{Any}())

julia> myfoo_3c = remotecall_fetch(2, ()->Main.foo_vec[3].c)
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> myfoo_3c = @getfrom(2,foo_vec[3].c)
3-element Array{Float64,1}:
 1.0
 1.0
 1.0
```
