### ISSUE TITLE
Test failure with julia 0.6 on Windows

### ISSUE THREAD

**Issue by Cody-G** [ChrisRackauckas/ParallelDataTransfer.jl#10]
This occurs on the both the tagged version and master.

```julia
julia> Pkg.test("ParallelDataTransfer")
INFO: Testing ParallelDataTransfer
Test Failed
  Expression: x == 3
   Evaluated: 1 == 3
ERROR: LoadError: There was an error during testing
while loading C:\Users\cody\.julia\v0.6\ParallelDataTransfer\test\runtests.jl, in expression starting on line 34
```

**Comment by Cody-G** [comment]
Oops, I see in REQUIRE that you're not supporting Julia 0.6.  Is support for 0.6 planned?  Thanks!

**Comment by ChrisRackauckas** [comment]
The REQUIRE only has a minimum version on v0.5, but yes tests are failing on v0.6. I hope to update this soon, but haven't gotten around to it.

**Comment by Cody-G** [comment]
Cool, thanks!  I would offer my help but I have almost no multithreading experience with Julia.  Also I'm out of the loop on what multithreading changes have been made in 0.6 and what's planned for 0.7...  That said, if you have some use for me let me know :)

**Comment by ChrisRackauckas** [comment]
Multithreading is shared memory. This library is for multiprocessing.

**Comment by Cody-G** [comment]
I know, though I didn't write it very clearly. I just thought the addition
of multithreading to Julia might change how you think about this package in
future Julia versions

**Comment by ChrisRackauckas** [comment]
I don't think multithreading will change this because multithreading doesn't need to pass data. But there are multithreading tools which are missing that I've thought about building a library for.

**Comment by Cody-G** [comment]
I see.  I had a thought that if one liked the interface of this package then they might want to use it to manage thread access to memory rather than moving data around.  In that case I suppose the name ParallelDataTransfer wouldn't be appropriate anymore.

**Comment by ChrisRackauckas** [comment]
Fixed. Will tag immediately after tests pass.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10504

Thanks for reminding me to do this.

**Comment by Cody-G** [comment]
Awesome, thank you!

**Comment by ChrisRackauckas** [comment]
The release is complete. Let me know if you need anything else.
