### ISSUE TITLE
Support for Julia 0.7 / 1.0

### ISSUE THREAD

**Issue by dylanfesta** [ChrisRackauckas/ParallelDataTransfer.jl#12]
Hi, thanks for providing these functions and macros.  I edited the code to make it compatible with 0.7 and 1.0 ... however the `@broadcast` macro throws an error. I just commented it out. The edited code is down here, and does not produce warnings or errors on 0.7 (I am not sufficiently experienced to propose any direct modification to the repository) 

[ParallelDataTransfer.jl.txt](https://github.com/ChrisRackauckas/ParallelDataTransfer.jl/files/2298346/ParallelDataTransfer.jl.txt)

[runtests.jl.txt](https://github.com/ChrisRackauckas/ParallelDataTransfer.jl/files/2298353/runtests.jl.txt)

**Comment by ChrisRackauckas** [comment]
Hey, looks great! Would you mind opening this up as a pull-request? You can use GitKraken to help you out, or use the web interface to make it from a branch.

**Comment by dylanfesta** [comment]
All done!  I am not sure how to handle backward compatibility, though.  And I have no idea how to fix "@broadcast"

**Comment by ChrisRackauckas** [comment]
Thanks!
