### ISSUE TITLE
Consecutive runs of sendto() abnormal timing

### ISSUE THREAD

**Issue by jchen975** [ChrisRackauckas/ParallelDataTransfer.jl#18]
Hi, I'm encountering some abnormal timing results when running a function with different number of workers, as below: 

```
Number of workers = 30 
Setting up pf time: 0.2516 seconds

Number of workers = 40 
Setting up pf time: 3.4781 seconds

Number of workers = 45
Setting up pf time: 3.9094 seconds

Number of workers = 50
Setting up pf time: 4.4384 seconds
```
The "Setting up pf time" is for sending  a dictionary (ndata), two 100 x 10000 matrices (PD, QD), and a integer (numPQ) to all workers, like so:
```
time = Base.time() 
sendto(workers(), ndata = network_data, P = PD, Q = QD, numPQ = numPQ) 
setup_time = Base.time() - time  # setting up overhead
```

Notice the initial time is more than ten times faster than the subsequent runs. The smaller increase between 40, 45 and 50 workers makes sense as there are more workers to send the data to. This was the result of submitting one job to cluster, where the bash script is like 
```
julia -p 30 run.jl
julia -p 40 run.jl
julia -p 45 run.jl
julia -p 50 run.jl
```

Similar patterns occur if I only run 40, 45 and 50. Then the set up time for 40 would be much faster than 45 and 50:
```
Number of workers = 40
Setting up pf time: 0.3801 seconds

Number of workers = 45
Setting up pf time: 3.977 seconds

Number of workers = 50
Setting up pf time: 4.2764 seconds
```

However, if I don't run them consecutively, and submit jobs containing only one line, it looks fine. Any ideas why that might be? 

There could be problems with another library I'm using to do the parallel computations as well, where I'm testing the best worker numbers for different cases. I'm noticing that the first run for each case is fast, but increases dramatically on the second run and slowly goes up as workers count increases. And when the next case starts running, the same thing happens. This is all happening in one job script like this:
```
julia -p 30 run.jl case1   # ok
julia -p 40 run.jl case1   # weird increase
# more for case 1 ...
julia -p 30 run.jl case2   # ok
julia -p 40 run.jl  case2  # weird increase
# more for case 2 ...
```

I'm happy to provide more details if you need, and thanks for your work!

**Comment by ChrisRackauckas** [comment]
I wonder if it has to do with whether it can do something async or not. I have no idea, but this is definitely Base parallelism behavior and not anything from this library.

**Comment by jchen975** [comment]
What do you mean by "it can do something async or not"? What are you referring to there? 

I guess for the time being I'll just run consecutive cases on the same worker count as a job and then submit multiple jobs for different worker counts.

**Comment by ChrisRackauckas** [comment]
>What do you mean by "it can do something async or not"? What are you referring to there?

I'm just saying I'm not sure what Base's serialization is doing, but it may be able to do some amount of async I/O. This library is probably the wrong level to ask this question since it's 100% an issue with the parallel implementation.
