### ISSUE TITLE
UndefVarError on remote processor

### ISSUE THREAD

**Issue by henry2004y** [ChrisRackauckas/ParallelDataTransfer.jl#20]
Hi, 

I have a question about using this package together with SharedArrays. If I want to allocate some processor local variables, the macro `@defineat` works well. However, the following does not work together with SharedArrays:
```
using Distributed
nprocs() == 1 && addprocs(2)

@everywhere using SharedArrays, ParallelDataTransfer

@everywhere function init(a::SharedArray)
   return 1
end

S = SharedArray{Int,2}((3,4), init=S -> setindex!.((S,),myid(),localindices(S)))

@defineat 2 x=3
#@spawnat 2 S
@defineat 2 x=init(S)

y = @getfrom 2 x
println(y)
```

It returns:
```
ERROR: On worker 2:
UndefVarError: S not defined
```

Interestingly, if I uncomment the one line in the above example, `@defineat 2 x=init(S)` will work. What is the reason behind this?

**Comment by ChrisRackauckas** [comment]
I do not know why that would be the case. Maybe SharedArrays are allocating themselves in a fairly odd way.

**Comment by henry2004y** [comment]
I did a quick search and found this [Q&A](https://stackoverflow.com/questions/35751420/shared-array-usage-in-julia) on StackOverFlow. So the reason is that although the underlying data is shared to all workers, the declaration of SharedArray is not. I think it makes sense.
