### ISSUE TITLE
Undefined export `@sendto`

### ISSUE THREAD

**Issue by Socob** [ChrisRackauckas/ParallelDataTransfer.jl#25]
https://github.com/ChrisRackauckas/ParallelDataTransfer.jl/blob/d6c6abf231bff7942c8bdccc118de9694cab4be9/src/ParallelDataTransfer.jl#L94

Seems to have been there since the initial commit in 6d8f73a37b, but never actually defined.

**Comment by ChrisRackauckas** [comment]
Yeah that can be deleted.
