### ISSUE TITLE
@broadcast does not broadcast to all workers at the same time

### ISSUE THREAD

**Issue by sbchisholm** [ChrisRackauckas/ParallelDataTransfer.jl#5]
I'm not sure if this was your original intent but I expected the macro `@broadcast` to execute the instruction on each worker at the same time but instead what happens is the function waits for a worker to complete the instruction before moving on to the next worker.

**Comment by ChrisRackauckas** [comment]
It just needs an @async on the function call in the loop. That should do it. I'm away from my computer so I can't test that right now.

**Comment by sbchisholm** [comment]
@ChrisRackauckas I'll give it a go, thanks for the quick response.  I just wasn't sure if you intended it to do it synchronously for a specific reason.
